describe("Muli-item Step - Multiple Bogeys", () => {
  beforeEach(() => {});
});

it("Should be able to add/edit/delete multiple items", () => {
  cy.visit("http://localhost:3000/");
  cy.findByRole("link", { name: /Multi-Item Form/ }).click();
  cy.findByText("Todo List").click();
  cy.findByText("Not Important").click();
  cy.findByText("Todo List").click();
  cy.findByText("Less Important").click();
  cy.findByText("Todo List").click();
  cy.findByText("Add Item").click();
  cy.wait(50);
  cy.findByLabelText("Part #").type("New Item");
  cy.get('[data-test="todo-description"]').type("Nice to have");
  cy.findByLabelText("Medium").click();
  cy.findAllByText("Confirm").click();
  cy.wait(50);
  cy.get('[data-test="edit-0"]').click();
  cy.findByLabelText("Part #").clear().type("Newer Item");
  cy.get('[data-test="todo-description"]').clear().type("Nicer to have");
  cy.findByLabelText("Low").click();
  cy.findAllByText("Confirm").click();
  cy.wait(50);
  cy.get('[data-test="edit-0"]').click();
  cy.wait(50);
  cy.findByText("Confirm").click();
  // Not sure why this needs to be here, but it does
  cy.findByText("Confirm").click();
  cy.wait(50);
  cy.get(".add-item-button").click();
  cy.findByLabelText("Part #").type("Second Item");
  cy.get('[data-test="todo-description"]').click().type("Second Item Descrip");
  cy.findAllByText("Confirm").click();
  cy.wait(50);
  cy.get('[data-test="edit-1"]').click();
  cy.findByLabelText("Part #").clear().type("Secondly Item");
  cy.get('[data-test="todo-description"]')
    .clear()
    .type("Seconder Item Descrip");
  cy.findByLabelText("Medium").click();
  cy.findAllByText("Confirm").click();
  cy.wait(50);
  cy.findByText("Add Item").click();
  cy.findByLabelText("Part #").type("Third Item");
  cy.get('[data-test="todo-description"]').click().type("Third Item Descrip");
  cy.findAllByText("Confirm").click();
  cy.wait(50);
  cy.get('[data-test="edit-2"]').click();
  cy.findByLabelText("Part #").clear().type("Thirdly Item");
  cy.get('[data-test="todo-description"]').clear().type("Thirder Item Descrip");
  cy.findByLabelText("Medium").click();
  cy.findByText("Confirm").click();
  cy.wait(50);
  cy.get('[data-test="delete-0"]').click();
  cy.findByText("Cancel").click();
  cy.wait(50);
  // cy.get('[data-test="delete-0"]').click();
  // cy.findByText("Confirm Delete").click();
  // cy.wait(50);
  // cy.get('[data-test="delete-1"]').click();
  // cy.findByText("Cancel").click();
  // cy.wait(50);
  // cy.get('[data-test="delete-1"]').click();
  // cy.findByText("Confirm Delete").click();
  // cy.wait(50);
  // cy.get('[data-test="delete-0"]').click();
  // cy.findByText("Cancel").click();
  // cy.wait(50);
  // cy.get('[data-test="delete-0"]').click();
  // cy.findByText("Confirm Delete").click();
  cy.findByText("Less Important").click();
  cy.findByText("Todo List").click();
  cy.findByText("Not Important").click();
  cy.findByText("Todo List").click();
});
